"""add setnull ondelete

Revision ID: 2c31c1758946
Revises: 0ab7662e5980
Create Date: 2021-01-18 20:31:07.812485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c31c1758946'
down_revision = '0ab7662e5980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('timer_predefined_timer_id_fkey', 'timer', type_='foreignkey')
    op.create_foreign_key(None, 'timer', 'predefined_timer', ['predefined_timer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timer', type_='foreignkey')
    op.create_foreign_key('timer_predefined_timer_id_fkey', 'timer', 'predefined_timer', ['predefined_timer_id'], ['id'])
    # ### end Alembic commands ###
